---
  - name: Git installation
    apt:
      pkg: git
      state: present
      update_cache: true
    become: true
  - name: Clone Rumba repository
    git:
      repo: https://github.com/joanllobera/hifi-collaborative-video
      dest: "{{ rumba_src_folder }}/rumba"
      version: master
