---
  - name: Install dependencies
    become: true
    apt:
      package: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - build-essential
      - python3-dev
      #- python-dev
      - python3-pip
      - python3.4-venv
      #- python-pip
      - libasound-dev
      - portaudio19-dev

    ###########################
    ###  Mongo installation ###
    ###########################

  - name: Install pymongo
    pip:
      name: pymongo
      executable: pip3
    become: true
  - name: Prepare mongodb installation
    become: true
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - name: Add mongodb sources
    shell: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.6.list
    become: true
  - name: Install mongodb
    become: true
    apt:
      package: mongodb-org
      state: present
      update_cache: true

    ##########################
    ## Backend installation ##
    ##########################

  #- name: Install virtualenv
  #  become: true
  #  pip:
  #    name: virtualenv
  #    executable: pip3
  - name: Create virtual environment
    #command: "virtualenv {{ rumba_src_folder }}//rumba/backend/venv -p python3"
    command: "python3 -m venv {{ rumba_src_folder }}/rumba/backend/venv --clear"
  - name: Install python dependencies
    become: true
    pip:
      name: egg
      chdir: "{{ rumba_src_folder }}/rumba/backend"
      extra_args: "-e {{ rumba_src_folder }}/rumba/backend"
      virtualenv: "{{ rumba_src_folder }}/rumba/backend/venv"
  - name: Create logs directory
    file:
      path: "{{ rumba_src_folder }}/rumba/backend/logs"
      state: directory

    ##########################
    ##   Rumba FS creation  ##
    ##########################
  - name: Create Rumba directories
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ubuntu_user }}"
      group: "{{ ubuntu_user }}"
    with_items:
      - /var/rumba
      - /var/rumba/logs
      - /var/rumba/sessions

    ##########################
    ## Microphone detection ##
    ##########################

  - name: Register to microphone events
    become: true
    copy:
      src: "{{ rumba_src_folder }}/rumba/utils/scripts/microphone/microphone_state.sh"
      dest: /etc/acpi/microphone_state.sh
      owner: root
      group: root
      mode: 0755
      remote_src: yes
  - name: Add microphone_plug event
    become: true
    copy:
      src: "{{ rumba_src_folder }}/rumba/utils/scripts/microphone/mic_pluged"
      dest: /etc/acpi/events/mic_pluged
      owner: root
      group: root
      mode: 0644
      remote_src: yes
  - name: Add microphone_unplug event
    become: true
    copy:
      src: "{{ rumba_src_folder }}/rumba/utils/scripts/microphone/mic_unpluged"
      dest: /etc/acpi/events/mic_unpluged
      owner: root
      group: root
      mode: 0644
      remote_src: yes
  - name: Restart ACPID service
    become: true
    service:
      name: acpid
      state: restarted
