---
  - name: Install dependencies
    become: true
    apt:
      package: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - build-essential
      - python3-dev
      - python-dev
      - python3-pip
      - python-pip
      - libasound-dev
      - portaudio19-dev

    ###########################
    ###  Mongo installation ###
    ###########################

  - name: Install pymongo
    pip:
      name: pymongo
    become: true
  - name: Prepare mongodb installation
    become: true
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - name: Add mongodb sources
    shell: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.6.list
    become: true
  - name: Install mongodb
    become: true
    apt:
      package: mongodb
      state: present
      update_cache: true

    ##########################
    ## Backend installation ##
    ##########################

  - name: Install virtualenv
    become: true
    pip:
      name: virtualenv
  - name: Create virtual environment
    command: "virtualenv {{ rumba_src_folder }}//rumba/backend/venv -p python3"
  - name: Install python dependencies
    become: true
    pip:
      name: egg
      chdir: "{{ rumba_src_folder }}/rumba/backend"
      extra_args: "-e {{ rumba_src_folder }}/rumba/backend"
      virtualenv: "{{ rumba_src_folder }}/rumba/backend/venv"
  - name: Create logs directory
    file:
      path: "{{ rumba_src_folder }}/rumba/backend/logs"
      state: directory

    ##########################
    ##   Rumba FS creation  ##
    ##########################
  - name: Create Rumba directories
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ubuntu_user }}"
      group: "{{ ubuntu_user }}"
    with_items:
      - /var/rumba
      - /var/rumba/logs
      - /var/rumba/sessions

    ##########################
    ## Microphone detection ##
    ##########################

 # after installation, execute this once to tell mobgo that the microphone is always plugged
 # /rumba/utils/scripts/microphone/microphone_state.sh on
 #
 #
